[client]
showSidebarNavigation = false

[theme]
primaryColor              = "#FF7533"
backgroundColor           = "#0D0D0D"
secondaryBackgroundColor  = "#161616"
textColor                 = "#E8E8E8"
font                      = "sans serif"
